model : 
  name : "dlrm"
  
  arch_feature_emb_size : 16
  arch_mlp_bot : [13, 512, 256, 64]
  arch_mlp_top : [512, 256, 1]
  arch_interaction_op : "dot"
  arch_interaction_itself : False
  sigmoid_bot : "relu"
  sigmoid_top : "relu"

  loss_function: "bce"
  # weighted_pooling: "learned"
  
  embedding_types:
    threshold : 100
    
    # custom :
    #   name : "qr_emb"
    #   qr_collisions : ""
    #   operation : "concat"
    #   mode : "sum"
    #   sparse : True
    
    base :
      name : "torch_bag"
      mode : "sum"
      sparse : True

  
  preproc :
    datafile : "<Your path to data>/criteo_dataset/train.txt"
    output_file : "kaggleAdDisplayChallenge_processed"
    dataset_config :
      name : "kaggle"
      dataset_multiprocessing : True
  
multiprocessing:
  num_aggregators : 1
  num_trainers : 1

  process_manager : 
    name : "ray"
    
  communications : 
    name : "kafka"
    serializer : "json"
    consumer : True
    producer : True
    consumer_port : 9092
    consumer_url : "127.0.0.1"
    consumer_topic : 'job-request'
    consumer_group_id : 'test-consumer-group'
    producer_port : 9092
    producer_url : "127.0.0.1"
    producer_topic : 'job-response'

trainer :
  name : dlrm
  config:
    batch_size : 128
    eval_batch_size : 512
    eval_every_n : 10000
    save_every_n : 5000
    num_workers : 10

  optimizer :
    name : "sgd"
    momentum : 0.9
    lr : 0.0001
    
  lr_scheduler :
    name : "dlrm"
    num_warmup_steps : 30000
    decay_start_step : 150000
    num_decay_steps : 150000

aggregator:
  name : "fed_avg"

random:
  data_seed : 100
  init_seed : 100
  model_seed : 100